# Gradle configuration
org.gradle.daemon=true
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.configureondemand=false

android.useAndroidX=true
android.enableJetifier=true
android.nonFinalResIds=false
android.nonTransitiveRClass=false
android.enableR8.fullMode=false

kapt.use.worker.api=true
kapt.incremental.apt=false

org.gradle.jvmargs=-Xmx5120M \
                    -Dfile.encoding=UTF-8 \
                    --add-opens jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED \
                    --add-opens jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED \
                    --add-opens jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED \
                    --add-opens jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED \
                    --add-opens jdk.compiler/com.sun.tools.javac.jvm=ALL-UNNAMED \
                    --add-opens jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED \
                    --add-opens jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED \
                    --add-opens jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED \
                    --add-exports jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED
