plugins {
    id 'com.android.library' // O 'com.android.application' si este módulo es la aplicación principal
    id 'org.jetbrains.kotlin.android'
    id 'com.google.protobuf'
}

android {
    // Si tu bloque 'android' está vacío o tiene configuraciones, asegúrate de que esté aquí.
    // (Por ejemplo: compileSdk 34, defaultConfig, etc., según lo que requiera tu proyecto)
}

OnVariants(selector().all()) { variant ->
        def baseVersionCode = android.defaultConfig.versionCode as int
        def buildVersionSuffix = project.hasProperty('buildSuffix') ? project.buildSuffix : "000"

        if (System.getenv("CI")) {
            println "baseVersionCode: $baseVersionCode"
            println "buildVersionSuffix: $buildVersionSuffix"
        }

        if (!buildVersionSuffix.matches("\\d{3}")) {
            throw new GradleException("buildSuffix must be a number with 3 digits: '$buildVersionSuffix'")
        }

        def abiVersionCodeMap = ["dogfood": 1, "x86": 2, "x86_64": 3, "armeabi-v7a": 4, "arm64-v8a": 5]

        variant.outputs.each { output ->
            def abiCode = 0
            def abiIdentifier = 'universal'

            if (variant.name.containsIgnoreCase('dogfood')) {
                abiCode = 1
            } else {
                def abiFilter = output.filters.find {
                    it.filterType == FilterConfiguration.FilterType.ABI
                }
                if (abiFilter != null) {
                    abiCode = abiVersionCodeMap.get(abiFilter.identifier) ?: 0
                    abiIdentifier = abiFilter.identifier
                }
            }
            if (System.getenv("CI")) {
                println "abiCode: $abiCode"
            }

            def finalVersionCode = (baseVersionCode.toString() + buildVersionSuffix + abiCode.toString()) as int
            output.versionCode.set(finalVersionCode)

            if (System.getenv("CI")) {
                println "ABI: ${abiIdentifier}, Final versionCode: ${finalVersionCode}"
            }
        }
    }


// Custom build check to enforce a maximum versionName length. Houston has an arbitrary max length
// of 40 chars for this and we sometimes add suffixes for dogfood app and/or debug builds.
afterEvaluate {
    def maxLength = 24
    def versionName = android.defaultConfig.versionName?.toString() ?: ""

    tasks.register("checkVersionNameLength") {
        doLast {
            if (versionName.length() > maxLength) {
                throw new GradleException(
                        "❌ versionName '${versionName}' exceeds ${maxLength} characters.\n" +
                                "Houston has size limit for this."
                )
            }
        }
    }

    tasks.named("preBuild").configure {
        dependsOn("checkVersionNameLength")
    }
}

apply plugin: 'com.google.gms.google-services' // Google Services plugin
// We should delete this as soon as we can. google services plugin introduces a dependency strict
// checking that checks against other projects deps too. There's a conflict with
// com.google.errorprone:error_prone_annotations. This should be fixed whenever the android deps
// bump the version of that lib.
googleServices { disableVersionCheck = true }

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:4.29.3"
    }
    plugins {
        grpc {
            artifact = "io.grpc:protoc-gen-grpc-java:$version_grpc"
        }
    }
    generateProtoTasks {
        all().each { task ->
            task.builtins {
                java { option 'lite' }
            }
            task.plugins {
                grpc { option 'lite' }
            }
        }
    }
}

